### PR TITLE
462 query account library

### PR DESCRIPTION
**Pull request by vakond**
Reworked contract QueryAccount to library.

### CODE REVIEW

**Review by s-medvedev — COMMENTED** [review]
Why we need the `QueryAccount.sol` file here and in proxy/testing/test_query_account_contract.py? As I can see it contains the same code.

**Comment by vakond** [comment]
This file (QueryAccount.sol) is for users. They will import it in their contracts to use.

As to integration test script `test_query_account_contract.py` in the proxy repo, it has the copy of the library to deploy testing contracts.

**Comment by s-medvedev** [comment]
> This file (QueryAccount.sol) is for users. They will import it in their contracts to use.
> 
> As to integration test script `test_query_account_contract.py` in the proxy repo, it has the copy of the library to deploy testing contracts.

Why we don't use `QueryAccount.sol` in the proxy repo in this case? Now we have two different implementation for QueryAccount library (with different style of comments). Moreover our tests doesn't check `QueryAccount.sol` library file.

**Comment by vakond** [comment]
> Why we don't use `QueryAccount.sol` in the proxy repo in this case? Now we have two different implementation for QueryAccount library (with different style of comments). Moreover our tests doesn't check `QueryAccount.sol` library file.

It seems we have to move `QueryAccount.sol` to a smart contract repository available from proxy tests. As such the test script proxy/testing/test_query_account_contract.py can use external .sol library, I think.

**Review by anton-lisanin — APPROVED** [review]

**Pull request merged**
