### PR TITLE
SLA-109 Use special constant for operator account inside the action list

### PR DESCRIPTION
**Pull request by s-medvedev**
NeonEVM puts `Action::ExternalInstriction` with the current operator on each iteration. If different operators executed iterations it leads to a problem, because on the final iteration, we have an action with the previous operator.

Solution: we put a special constant to the action list and change this constant with the real operator in the final iteration.

### CODE REVIEW

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0009827145609504 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.25205708e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 8.347047200000002e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 6.2602854e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 4.590875960000001e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0033274001194304 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0019862967399008 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0019696026455008004 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0010411438913504 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   75033 |      0     |      0.077 |    0.000658737 |         0     |
| getAccountInfo                    |   54478 |      0     |      0.063 |    0.00122125  |         0     |
| getBlocks                         |   28629 |      0     |      0.029 |    0.000431136 |         0     |
| getTransaction                    |   23949 |      0     |      0.09  |    0.00299787  |         0.001 |
| sendTransaction                   |   21880 |      0     |      0.132 |    0.0033739   |         0.002 |
| getBlock                          |   14367 |      0     |      0.028 |    0.000802116 |         0.001 |
| getMultipleAccounts               |    9341 |      0     |      0.069 |    0.00192603  |         0.001 |
| getBlockTime                      |    5921 |      0     |      0.07  |    0.000493836 |         0     |
| getLatestBlockhash                |    4474 |      0     |      0.091 |    0.00198391  |         0.001 |
| getBalance                        |    1762 |      0     |      0.027 |    0.00115607  |         0     |
| getSignatureStatuses              |    1027 |      0     |      0.04  |    0.000945472 |         0     |
| getVersion                        |     535 |      0     |      0.026 |    0.00119065  |         0     |
| isBlockhashValid                  |     495 |      0     |      0.014 |    0.000349495 |         0     |
| getSignaturesForAddress           |     135 |      0     |      0.008 |    0.00139259  |         0.001 |
| requestAirdrop                    |      32 |      0     |      0.002 |    0.0006875   |         0.001 |
| simulateTransaction               |      23 |      0     |      0.001 |    0.000347826 |         0     |
| getHealth                         |       3 |      0     |      0.001 |    0.000333333 |         0     |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000666667 |         0.001 |
| getFirstAvailableBlock            |       2 |      0     |      0     |    0           |         0     |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |         0     |
| getClusterNodes                   |       1 |      0.089 |      0.089 |    0.089       |         0.089 |

</details>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0009827145609504 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.25205708e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 8.347047200000002e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 6.2602854e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 4.590875960000001e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0033274001194304 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0019862967399008 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0019696026455008004 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0010411438913504 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   76479 |      0     |      0.378 |    0.000493966 |         0     |
| getAccountInfo                    |   54134 |      0     |      0.096 |    0.000946743 |         0     |
| getBlocks                         |   28521 |      0     |      0.04  |    0.000294976 |         0     |
| getTransaction                    |   26852 |      0     |      0.127 |    0.00267191  |         0.001 |
| sendTransaction                   |   24800 |      0     |      0.124 |    0.00269762  |         0.002 |
| getBlock                          |   14315 |      0     |      0.024 |    0.000647153 |         0.001 |
| getMultipleAccounts               |    8975 |      0     |      0.081 |    0.00157136  |         0.001 |
| getBlockTime                      |    5741 |      0     |      0.03  |    0.000351681 |         0     |
| getLatestBlockhash                |    4446 |      0     |      0.124 |    0.00166059  |         0     |
| getBalance                        |    1755 |      0     |      0.095 |    0.000981766 |         0     |
| getSignatureStatuses              |    1010 |      0     |      0.016 |    0.000588119 |         0     |
| getVersion                        |     526 |      0     |      0.026 |    0.000608365 |         0     |
| isBlockhashValid                  |     487 |      0     |      0.011 |    0.000310062 |         0     |
| getSignaturesForAddress           |     139 |      0     |      0.011 |    0.00159712  |         0.001 |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.00040625  |         0     |
| simulateTransaction               |      23 |      0     |      0.001 |    0.000304348 |         0     |
| getHealth                         |       3 |      0     |      0.001 |    0.000333333 |         0     |
| getTokenAccountBalance            |       3 |      0     |      0     |    0           |         0     |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |         0     |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |         0.001 |

</details>

**Review by anton-lisanin — APPROVED** [review]

**Pull request merged**
