### PR TITLE
NDEV-3266. Set gas_price in Transaction from TxParams

### PR DESCRIPTION
**Pull request by ancientmage**

### CODE REVIEW

**Review by evgenyzdanovich — DISMISSED** [review]

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.00083410568 | 10 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0008341291264 | 10 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0028363464064 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00477928 | 0.0017002766528000002 | 5 | 10 | 2644640 | 2389640 | 90.36 | 
| Repay | 0.00011 | 3.91336e-05 | 5 | 10 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00473928 | 0.0016860462528000002 | 4 | 7 | 2634640 | 2369640 | 89.94 | 
| Withdraw | 7e-05 | 2.49032e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00247464 | 0.0008803779264000001 | 5 | 11 | 1752320 | 1237320 | 70.61 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0008341291264 | 10 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02747064 | 0.0097729548864 | 4 | 7 | 14000320 | 13735320 | 98.11 | 
| NonfungiblePositionManager - Increase liquidity  | 8e-05 | 2.8460000000000002e-05 | 23 | 6 | 230000 | 40000 | 17.39 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0004973809408 | 18 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 2e-05 | 7.115200000000001e-06 | 21 | 1 | 80000 | 10000 | 12.5 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 7.115200000000001e-06 | 16 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 7.115200000000001e-06 | 18 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00017053711360000002 | 12 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0008341291264 | 13 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0008376867264 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 7.115200000000001e-06 | 22 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 7.115200000000001e-06 | 22 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 7.115200000000001e-06 | 24 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00241464 | 0.0008590323264 | 4 | 7 | 1492320 | 1207320 | 80.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 7.115200000000001e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 7.115200000000001e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 7.115200000000001e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.06728e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00241464 | 0.0008590323264 | 4 | 7 | 1522320 | 1207320 | 79.31 | 
| Swap SUSD -> LP metapool | 2e-05 | 7.115200000000001e-06 | 23 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 5.3364e-05 | 5 | 11 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00013 | 4.62488e-05 | 4 | 7 | 330000 | 65000 | 19.7 | 
| Remove liquidity in Metapool | 2e-05 | 7.1154e-06 | 24 | 1 | 100000 | 10000 | 10.0 |

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   59462 |      0     |      0.135 |    0.000893394 |         0     |
| getAccountInfo                    |   58033 |      0     |      0.109 |    0.00143079  |         0     |
| getBlocks                         |   23718 |      0     |      0.043 |    0.000649802 |         0     |
| getBlock                          |   15556 |      0     |      0.05  |    0.00143044  |         0.001 |
| getMultipleAccounts               |   13952 |      0     |      0.117 |    0.00199126  |         0.001 |
| getTransaction                    |    8012 |      0     |      0.143 |    0.0104068   |         0.004 |
| getBlockTime                      |    6214 |      0     |      0.117 |    0.000536209 |         0     |
| sendTransaction                   |    5168 |      0     |      0.117 |    0.00839861  |         0.004 |
| getLatestBlockhash                |    4965 |      0     |      0.16  |    0.00246848  |         0.001 |
| getBalance                        |    1816 |      0     |      0.051 |    0.00145815  |         0.001 |
| getSignatureStatuses              |    1098 |      0     |      0.082 |    0.0013643   |         0     |
| getVersion                        |     573 |      0     |      0.032 |    0.00135951  |         0     |
| isBlockhashValid                  |     531 |      0     |      0.017 |    0.000429379 |         0     |
| getSignaturesForAddress           |      60 |      0     |      0.005 |    0.0014      |         0.001 |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000421053 |         0     |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.000625    |         0.001 |
| getHealth                         |       3 |      0     |      0.026 |    0.009       |         0.001 |
| getTokenAccountBalance            |       3 |      0     |      0     |    0           |         0     |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |         0.001 |
| getClusterNodes                   |       1 |      0     |      0     |    0           |         0     |

</details>

**Review by s-medvedev — DISMISSED** [review]

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Review by s-medvedev — APPROVED** [review]

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

🔗[Cost report](https://github.com/neonlabsorg/neon-proxy.py/actions/runs/10735697123/artifacts/1900459552)

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   62126 |      0     |      0.231 |    0.000996089 |         0     |
| getAccountInfo                    |   59166 |      0     |      0.17  |    0.0017001   |         0     |
| getBlocks                         |   24505 |      0     |      0.156 |    0.00071463  |         0     |
| getBlock                          |   15295 |      0     |      0.092 |    0.00151219  |         0.001 |
| getMultipleAccounts               |   14138 |      0     |      0.097 |    0.00219147  |         0.001 |
| getLatestBlockhash                |   11490 |      0     |      0.146 |    0.00165239  |         0     |
| getTransaction                    |    8099 |      0     |      0.217 |    0.00965119  |         0.004 |
| getBlockTime                      |    6303 |      0     |      0.064 |    0.000567666 |         0     |
| sendTransaction                   |    5260 |      0     |      0.176 |    0.00789905  |         0.003 |
| getBalance                        |    1847 |      0     |      0.077 |    0.00156903  |         0.001 |
| getSignatureStatuses              |    1168 |      0     |      0.06  |    0.00124486  |         0     |
| getVersion                        |     626 |      0     |      0.09  |    0.00172364  |         0     |
| isBlockhashValid                  |     566 |      0     |      0.027 |    0.000392226 |         0     |
| getSignaturesForAddress           |      57 |      0     |      0.002 |    0.000947368 |         0.001 |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000394737 |         0     |
| requestAirdrop                    |      32 |      0     |      0.002 |    0.00084375  |         0.001 |
| getTokenAccountBalance            |      12 |      0     |      0.073 |    0.00675     |         0.001 |
| getHealth                         |       3 |      0     |      0.001 |    0.000333333 |         0     |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |         0     |
| getClusterNodes                   |       1 |      0     |      0     |    0           |         0     |

</details>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

🔗[Cost report](https://github.com/neonlabsorg/neon-proxy.py/actions/runs/10739172434/artifacts/1901389907)

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   64241 |          0 |      0.265 |    0.000748743 |        0      |
| getAccountInfo                    |   59405 |          0 |      0.091 |    0.00116549  |        0      |
| getBlocks                         |   25693 |          0 |      0.142 |    0.000588915 |        0      |
| getBlock                          |   16615 |          0 |      0.042 |    0.00122094  |        0.001  |
| getMultipleAccounts               |   14480 |          0 |      0.182 |    0.00163626  |        0.001  |
| getLatestBlockhash                |   11665 |          0 |      0.083 |    0.00121766  |        0      |
| getTransaction                    |    8129 |          0 |      0.223 |    0.00815845  |        0.003  |
| getBlockTime                      |    6351 |          0 |      0.042 |    0.000406708 |        0      |
| sendTransaction                   |    5288 |          0 |      0.155 |    0.00709191  |        0.003  |
| getBalance                        |    1853 |          0 |      0.046 |    0.00119752  |        0      |
| getSignatureStatuses              |    1184 |          0 |      0.02  |    0.000873311 |        0      |
| getVersion                        |     618 |          0 |      0.056 |    0.00104045  |        0      |
| isBlockhashValid                  |     574 |          0 |      0.002 |    0.000275261 |        0      |
| getSignaturesForAddress           |      62 |          0 |      0.009 |    0.00114516  |        0.001  |
| simulateTransaction               |      38 |          0 |      0.001 |    0.000342105 |        0      |
| requestAirdrop                    |      32 |          0 |      0.002 |    0.000625    |        0.001  |
| getTokenAccountBalance            |       4 |          0 |      0.001 |    0.00025     |        0      |
| getHealth                         |       3 |          0 |      0.001 |    0.000666667 |        0.001  |
| getFirstAvailableBlock            |       2 |          0 |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |          0 |      0     |    0           |        0      |
| getClusterNodes                   |       1 |          0 |      0     |    0           |        0      |

</details>

**Pull request merged**
