### PR TITLE
SLA-99 Do not track update accounts for specific owners (#485)

### PR DESCRIPTION
**Pull request by s-medvedev**
* SLA-99 Do not track update accounts for specific owners

---------

### CODE REVIEW

**Review by evgenyzdanovich — DISMISSED** [review]
LGTM

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009804518017184 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114789602865784 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50905534e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005846635365664 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019526477440623999 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.363465000000001e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.3632672e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.0002004507882496 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009804425403904 | 12 | 1 | 1202320 | 1172320 | 97.5 |

**Review by evgenyzdanovich — APPROVED** [review]
LGTM

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0009827145609504 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.25205708e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 8.347047200000002e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 6.2602854e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 4.590875960000001e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0033274001194304 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0019862967399008 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0019696026455008004 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0010411438913504 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   70542 |      0     |      0.586 |    0.00115927  |         0.001 |
| getAccountInfo                    |   54959 |      0     |      0.115 |    0.00214542  |         0.001 |
| getBlocks                         |   28351 |      0     |      0.073 |    0.000710592 |         0.001 |
| getTransaction                    |   20739 |      0     |      0.119 |    0.00520493  |         0.002 |
| sendTransaction                   |   18641 |      0     |      0.115 |    0.00554595  |         0.003 |
| getBlock                          |   14245 |      0     |      0.053 |    0.00138406  |         0.001 |
| getMultipleAccounts               |    9495 |      0     |      0.115 |    0.00295134  |         0.001 |
| getBlockTime                      |    5992 |      0     |      0.086 |    0.000926068 |         0     |
| getLatestBlockhash                |    4504 |      0     |      0.094 |    0.00261723  |         0.001 |
| getBalance                        |    1771 |      0     |      0.047 |    0.00188368  |         0.001 |
| getSignatureStatuses              |    1031 |      0     |      0.039 |    0.00177304  |         0.001 |
| getVersion                        |     537 |      0     |      0.029 |    0.00180074  |         0.001 |
| isBlockhashValid                  |     497 |      0     |      0.024 |    0.000798793 |         0     |
| getSignaturesForAddress           |     134 |      0     |      0.006 |    0.00212687  |         0.002 |
| simulateTransaction               |      41 |      0     |      0.001 |    0.000707317 |         0.001 |
| requestAirdrop                    |      32 |      0.001 |      0.002 |    0.001125    |         0.001 |
| getHealth                         |       3 |      0     |      0.001 |    0.000333333 |         0     |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000333333 |         0     |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |         0     |
| getClusterNodes                   |       1 |      0     |      0     |    0           |         0     |

</details>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0009827145609504 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1492320 | 1197320 | 80.23 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 8.347047200000002e-06 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.25205708e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00239464 | 0.0009994086553504 | 4 | 5 | 1522320 | 1197320 | 78.65 | 
| Swap SUSD -> LP metapool | 2e-05 | 8.347047200000002e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 6.2602854e-05 | 5 | 9 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00011 | 4.590875960000001e-05 | 4 | 5 | 330000 | 55000 | 16.67 | 
| Remove liquidity in Metapool | 2e-05 | 8.347047200000002e-06 | 23 | 1 | 100000 | 10000 | 10.0 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0033274001194304 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00475928 | 0.0019862967399008 | 5 | 8 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00471928 | 0.0019696026455008004 | 4 | 5 | 2634640 | 2359640 | 89.56 | 
| Withdraw | 0.00011 | 4.590875960000001e-05 | 5 | 8 | 250000 | 55000 | 22.0 | 
| Liquidation | 0.00249464 | 0.0010411438913504 | 5 | 11 | 1752320 | 1247320 | 71.18 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0009785410373504 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02745064 | 0.0114565893875104 | 4 | 5 | 14000320 | 13725320 | 98.04 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 2.50411416e-05 | 23 | 4 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0005834919874688 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0019487350275008 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 8.347047200000002e-06 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 8.347047200000002e-06 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00020006202728960003 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0009785410373504 | 12 | 1 | 1202320 | 1172320 | 97.5 |

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   73217 |      0     |      0.185 |    0.00130184  |        0.001  |
| getAccountInfo                    |   54327 |      0     |      0.187 |    0.00270039  |        0.001  |
| getBlocks                         |   27508 |      0     |      0.069 |    0.000754181 |        0.001  |
| getTransaction                    |   23649 |      0     |      0.187 |    0.00568747  |        0.002  |
| sendTransaction                   |   21594 |      0     |      0.113 |    0.00558405  |        0.003  |
| getBlock                          |   13817 |      0     |      0.058 |    0.00145965  |        0.001  |
| getMultipleAccounts               |    9149 |      0     |      0.149 |    0.0037309   |        0.001  |
| getBlockTime                      |    5841 |      0     |      0.072 |    0.00127307  |        0.001  |
| getLatestBlockhash                |    4473 |      0     |      0.162 |    0.00321306  |        0.001  |
| getBalance                        |    1757 |      0     |      0.06  |    0.00251053  |        0.001  |
| getSignatureStatuses              |    1046 |      0     |      0.095 |    0.0027543   |        0.001  |
| getVersion                        |     544 |      0     |      0.151 |    0.00256801  |        0.001  |
| isBlockhashValid                  |     505 |      0     |      0.03  |    0.00107129  |        0.001  |
| getSignaturesForAddress           |     140 |      0.001 |      0.033 |    0.00300714  |        0.002  |
| requestAirdrop                    |      32 |      0.001 |      0.002 |    0.0011875   |        0.001  |
| simulateTransaction               |      23 |      0     |      0.001 |    8.69565e-05 |        0      |
| getHealth                         |       5 |      0     |      0.001 |    0.0008      |        0.001  |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000333333 |        0      |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |        0.001  |
| getClusterNodes                   |       1 |      0     |      0     |    0           |        0      |

</details>

**Pull request merged**
