### PR TITLE
Ndev 3279 get accounts in tx

### PR DESCRIPTION
**Pull request by iguberman**

### CODE REVIEW

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

🔗[Cost report](https://github.com/neonlabsorg/neon-proxy.py/actions/runs/10780747826/artifacts/1911226065)

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   60360 |      0     |      0.174 |    0.000823989 |        0      |
| getAccountInfo                    |   59417 |      0     |      0.173 |    0.00131993  |        0      |
| getBlocks                         |   23764 |      0     |      0.083 |    0.000649638 |        0      |
| getBlock                          |   15425 |      0     |      0.17  |    0.00135637  |        0.001  |
| getMultipleAccounts               |   14052 |      0     |      0.153 |    0.00181704  |        0.001  |
| getLatestBlockhash                |   11205 |      0     |      0.102 |    0.00130424  |        0      |
| getTransaction                    |    8173 |      0     |      0.129 |    0.00993479  |        0.004  |
| getBlockTime                      |    6351 |      0     |      0.027 |    0.000427177 |        0      |
| sendTransaction                   |    5330 |      0     |      0.176 |    0.00717692  |        0.003  |
| getBalance                        |    1861 |      0     |      0.095 |    0.00138474  |        0.001  |
| getSignatureStatuses              |    1181 |      0     |      0.118 |    0.00121084  |        0      |
| getVersion                        |     629 |      0     |      0.075 |    0.00150715  |        0      |
| isBlockhashValid                  |     572 |      0     |      0.016 |    0.000402098 |        0      |
| getSignaturesForAddress           |      61 |      0     |      0.009 |    0.00129508  |        0.001  |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000368421 |        0      |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.0006875   |        0.001  |
| getTokenAccountBalance            |      10 |      0     |      0.001 |    0.0005      |        0.0005 |
| getHealth                         |       3 |      0     |      0.004 |    0.00133333  |        0      |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |        0.001  |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |        0.001  |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |        0.001  |

</details>

**Review by ancientmage — DISMISSED** [review]

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

🔗[Cost report](https://github.com/neonlabsorg/neon-proxy.py/actions/runs/10805053039/artifacts/1917742040)

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   61245 |      0     |      0.14  |    0.000632623 |        0      |
| getAccountInfo                    |   58901 |      0     |      0.082 |    0.000883482 |        0      |
| getBlocks                         |   24145 |      0     |      0.205 |    0.000471443 |        0      |
| getBlock                          |   15639 |      0     |      0.028 |    0.00095556  |        0.001  |
| getMultipleAccounts               |   14074 |      0     |      0.183 |    0.00137971  |        0.001  |
| getLatestBlockhash                |   10614 |      0     |      0.093 |    0.00131477  |        0      |
| getTransaction                    |    8078 |      0     |      0.089 |    0.00779686  |        0.003  |
| getBlockTime                      |    6285 |      0     |      0.079 |    0.000275099 |        0      |
| sendTransaction                   |    5261 |      0     |      0.098 |    0.00741019  |        0.003  |
| getBalance                        |    1841 |      0     |      0.028 |    0.000846822 |        0      |
| getSignatureStatuses              |    1186 |      0     |      0.027 |    0.000611298 |        0      |
| getVersion                        |     621 |      0     |      0.017 |    0.000624799 |        0      |
| isBlockhashValid                  |     575 |      0     |      0.01  |    0.000248696 |        0      |
| getSignaturesForAddress           |      61 |      0     |      0.006 |    0.00109836  |        0.001  |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000184211 |        0      |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.0004375   |        0      |
| getTokenAccountBalance            |       5 |      0     |      0.001 |    0.0002      |        0      |
| getHealth                         |       3 |      0.001 |      0.01  |    0.004       |        0.001  |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |        0      |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |        0.001  |

</details>

**Review by s-medvedev — APPROVED** [review]

**Pull request merged**
