### PR TITLE
NDEV-3265. Fix /api/emulate failed with precompiled contracts

### PR DESCRIPTION
**Pull request by ancientmage**

### CODE REVIEW

**Review by evgenyzdanovich — APPROVED** [review]

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0008150906496 | 10 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0008150906496 | 10 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0027716085696 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00477928 | 0.0016614688992000002 | 5 | 10 | 2644640 | 2389640 | 90.36 | 
| Repay | 0.00013 | 4.51932e-05 | 5 | 10 | 290000 | 65000 | 22.41 | 
| Flashloan | 0.00473928 | 0.0016475632992000002 | 4 | 7 | 2634640 | 2369640 | 89.94 | 
| Withdraw | 7e-05 | 2.43348e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00247464 | 0.0008602838496 | 5 | 11 | 1752320 | 1237320 | 70.61 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0008150437567999999 | 10 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02747064 | 0.0095496185832 | 4 | 7 | 14000320 | 13735320 | 98.11 | 
| NonfungiblePositionManager - Increase liquidity  | 8e-05 | 2.78104e-05 | 23 | 6 | 230000 | 40000 | 17.39 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.00048601455039999994 | 18 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 2e-05 | 6.9526e-06 | 21 | 1 | 80000 | 10000 | 12.5 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 6.9526e-06 | 16 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 6.9526e-06 | 18 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.0001666351232 | 12 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0008150672032 | 13 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0008185199567999999 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 6.9526e-06 | 22 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 6.9524000000000006e-06 | 22 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 3e-05 | 1.04286e-05 | 4 | 2 | 100000 | 15000 | 15.0 | 
| Add liquidity in 3 Tokens | 0.00241464 | 0.0008394013032 | 4 | 7 | 1492320 | 1207320 | 80.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 6.9524000000000006e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 6.9526e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 6.9524000000000006e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.04289e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00241464 | 0.0008394013032 | 4 | 7 | 1522320 | 1207320 | 79.31 | 
| Swap SUSD -> LP metapool | 2e-05 | 6.9526e-06 | 23 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 5.2144499999999995e-05 | 5 | 11 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00013 | 4.51919e-05 | 4 | 7 | 330000 | 65000 | 19.7 | 
| Remove liquidity in Metapool | 3e-05 | 1.04286e-05 | 4 | 2 | 100000 | 15000 | 15.0 |

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getAccountInfo                    |   59357 |      0     |      0.155 |    0.00234011  |        0.001  |
| getSlot                           |   55950 |      0     |      0.151 |    0.00133405  |        0.001  |
| getBlocks                         |   21985 |      0     |      0.167 |    0.000885877 |        0.001  |
| getBlock                          |   14588 |      0     |      0.186 |    0.00218316  |        0.002  |
| getMultipleAccounts               |   14020 |      0     |      0.139 |    0.00294344  |        0.001  |
| getLatestBlockhash                |   10886 |      0     |      0.144 |    0.00215543  |        0.001  |
| getTransaction                    |    8151 |      0     |      0.23  |    0.0134514   |        0.005  |
| getBlockTime                      |    6444 |      0     |      0.138 |    0.000890906 |        0      |
| sendTransaction                   |    5300 |      0     |      0.143 |    0.0107958   |        0.005  |
| getBalance                        |    1851 |      0     |      0.057 |    0.00248082  |        0.001  |
| getSignatureStatuses              |    1186 |      0     |      0.149 |    0.00244857  |        0.001  |
| getVersion                        |     619 |      0     |      0.144 |    0.00245073  |        0.001  |
| isBlockhashValid                  |     575 |      0     |      0.028 |    0.000888696 |        0      |
| getSignaturesForAddress           |      61 |      0     |      0.152 |    0.00455738  |        0.002  |
| simulateTransaction               |      38 |      0     |      0.003 |    0.000657895 |        0.001  |
| requestAirdrop                    |      32 |      0     |      0.002 |    0.00090625  |        0.001  |
| getTokenAccountBalance            |       4 |      0     |      0.001 |    0.0005      |        0.0005 |
| getHealth                         |       3 |      0     |      0.002 |    0.001       |        0.001  |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |        0.001  |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |        0.001  |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |        0.001  |

</details>

**Review by s-medvedev — APPROVED** [review]

**Pull request merged**
