### PR TITLE
NDEV-2392: Update Solana to v1.17.22

### PR DESCRIPTION
**Pull request by andreisilviudragnea**
- Updated Solana to v1.17.20.
- Added `metaplex` feature, which is currently disabled, because [mpl-token-metadata](https://crates.io/crates/mpl-token-metadata) does not contain program code of `token-metadata` Solana program anymore. I opened an issue [here](https://github.com/metaplex-foundation/mpl-token-metadata/issues/80) asking about how to use `token-metadata` Solana program code. I tried using the program specified as a Cargo git dependency, but it does not support Solana v1.17 yet.
- Fixed or disabled new Cargo clippy warnings.
- Migrated to using `cargo build-sbf` instead of `cargo build-bpf`.

The progress of Metaplex discussions is [here](https://github.com/metaplex-foundation/mpl-token-metadata/issues/80)

### CODE REVIEW

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.002997179331136 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.035751828301344 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.000576138904 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0018306551793279998 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.005968170530272 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.6196125000000003e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.61932748e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0006278249728128001 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.0029981113498688 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.0030112094876688002 | 3 | 2 | 3181920 | 1149480 | 36.13 | 
| Swap DAI -> USDC | 2e-05 | 2.6196275600000003e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.6197492600000002e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.6197492600000002e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.0036535764781024 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.62002992e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.62002992e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.62002992e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.93004488e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.0037452803700415995 | 3 | 31 | 3271920 | 1429480 | 43.69 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.62002992e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0013493154088000002 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0007336083776 | 4 | 29 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.62002992e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.0029985718428416 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.0029985718428416 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.010199252472576 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.0066652513152832 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0006419073303999999 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.006573550268083201 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 9.17010472e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0044002878500416 | 4 | 57 | 4940000 | 1679480 | 34.0 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0028369015222303997 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.033840183527467205 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0005453328452000001 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0017327586677791998 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.0056490153546608 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.4787689800000003e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.4789198400000004e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0005941475072512001 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.0028370741784832 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.0028494687776832004 | 3 | 2 | 3181920 | 1149480 | 36.13 | 
| Swap DAI -> USDC | 2e-05 | 2.4789198400000004e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.4791e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.4791e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.003457055368 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.4791e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.4791e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.4791e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.71872239e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.0035438928547048 | 3 | 31 | 3271920 | 1429480 | 43.69 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.4791482600000002e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0012767613539000002 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0006941615127999999 | 4 | 29 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.4791482600000002e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.0028373356006048 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.0028373356006048 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.009650828346528001 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.0063068540075096 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0006073108608 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.0062192598257664 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 8.675869439999998e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0041631283448832 | 4 | 57 | 4940000 | 1679480 | 34.0 |

**Comment by stanislav-tkach** [comment]
I'm also interested in updating the Solana version to v1.17.20. Hopefully this can be merged soon.

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0024166699137856003 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.0288272266264224 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.00046454929840000005 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0014760842797888 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.0048122239503712 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.1115877200000003e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.1115877200000003e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0005061053447296001 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.0024166699137856003 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.0024272278523856 | 3 | 2 | 3181920 | 1149480 | 36.13 | 
| Swap DAI -> USDC | 2e-05 | 2.1115877200000003e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.1115877200000003e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.1115877200000003e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.0029445668437856004 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.1115877200000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.1115877200000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.1115877200000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.16738158e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.0030184724139856 | 3 | 31 | 3271920 | 1429480 | 43.69 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.1115877200000003e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0010874676758000001 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0005912445616 | 4 | 29 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.1115877200000003e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.0024166699137856003 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.0024166699137856003 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.008219988676416 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.005371794696171201 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0005173389914000001 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.0052978891259712006 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 7.39055702e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0035463693439856 | 4 | 57 | 4940000 | 1679480 | 34.0 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.0029543648150176004 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.0029543648150176004 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.010048888011936001 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.006566987553135201 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0006324438869000001 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.0064766384264352 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 9.034912669999999e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0043354157517176 | 4 | 57 | 4940000 | 1679480 | 34.0 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0029543648150176004 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.0352411157079504 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0005679087964000001 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0018045043865248 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.0058829155938352005 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.5814036200000002e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.5814036200000002e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0006187108196416001 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.0029543648150176004 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.0029672718331176 | 3 | 2 | 3181920 | 1149480 | 36.13 | 
| Swap DAI -> USDC | 2e-05 | 2.5814036200000002e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.5814036200000002e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.5814036200000002e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.0035997157200176 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.5814036200000002e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.5814036200000002e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.5814036200000002e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.87210543e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.0036900648467176 | 3 | 31 | 3271920 | 1429480 | 43.69 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.5814036200000002e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0013294228643 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0007227930135999999 | 4 | 30 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.5814036200000002e-05 | 23 | 1 | 1937440 | 10000 | 0.52 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00233072 | 0.0028024684959264 | 9 | 1 | 1185360 | 1165360 | 98.31 | 
| Token approve | 0.00233072 | 0.0028024684959264 | 9 | 1 | 1185360 | 1165360 | 98.31 | 
| Deposit to lending pool | 0.00791088 | 0.009512078660265601 | 4 | 5 | 4824480 | 3955440 | 81.99 | 
| Borrow from lending pool | 0.00517144 | 0.006218163348052801 | 4 | 30 | 3779120 | 2585720 | 68.42 | 
| Repay | 0.00049 | 0.0005891782638 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00510144 | 0.0061339950246527995 | 4 | 28 | 7464880 | 2550720 | 34.17 | 
| Withdraw | 7e-05 | 8.41683234e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00340072 | 0.0040890414393264 | 4 | 57 | 4731200 | 1700360 | 35.94 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00233072 | 0.0028024684959264 | 9 | 1 | 1185360 | 1165360 | 98.31 | 
| NonfungiblePositionManager - Mint position | 0.02772144 | 0.0333323875290528 | 4 | 28 | 31261120 | 13860720 | 44.34 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0005290580328 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0016810578511295999 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00464144 | 0.0055808888994528 | 20 | 1 | 3539120 | 2320720 | 65.57 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.4048092400000002e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.4048092400000002e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0005763846786432 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00233072 | 0.0028024684959264 | 12 | 1 | 1654720 | 1165360 | 70.43 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234072 | 0.0028144925421264002 | 3 | 2 | 3202800 | 1170360 | 36.54 | 
| Swap DAI -> USDC | 2e-05 | 2.4048092400000002e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.4048092400000002e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.4048092400000002e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00283072 | 0.0034036708059264004 | 4 | 30 | 4241520 | 1415360 | 33.37 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.4048092400000002e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.4048092400000002e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.4048092400000002e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.6072138600000003e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00290072 | 0.0034878391293264 | 3 | 31 | 3292800 | 1450360 | 44.05 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.4048092400000002e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0012384767586000002 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0006733465872 | 4 | 30 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.4048092400000002e-05 | 23 | 1 | 1937440 | 10000 | 0.52 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00233072 | 0.0027546432635792003 | 9 | 1 | 1185360 | 1165360 | 98.31 | 
| Token approve | 0.00233072 | 0.0027546083027792 | 9 | 1 | 1185360 | 1165360 | 98.31 | 
| Deposit to lending pool | 0.00791088 | 0.0093454009278672 | 4 | 5 | 4824480 | 3955440 | 81.99 | 
| Borrow from lending pool | 0.00517144 | 0.0061094932418984 | 4 | 30 | 3779120 | 2585720 | 68.42 | 
| Repay | 0.00049 | 0.0005788525526 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00510144 | 0.0060251694230976 | 4 | 28 | 7464880 | 2550720 | 34.17 | 
| Withdraw | 7e-05 | 8.26750603e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00340072 | 0.0040167734867648 | 4 | 57 | 4960880 | 1700360 | 34.28 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00233072 | 0.0027527644934944003 | 9 | 1 | 1185360 | 1165360 | 98.31 | 
| NonfungiblePositionManager - Mint position | 0.02772144 | 0.0327372971980752 | 4 | 28 | 31261120 | 13860720 | 44.34 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0005196126452 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0016513866229823997 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00464144 | 0.0054814775628304006 | 20 | 1 | 3539120 | 2320720 | 65.57 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.36237372e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.36237372e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0005661514691392 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00233072 | 0.0027527131011184 | 12 | 1 | 1654720 | 1165360 | 70.43 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234072 | 0.002764417121244 | 3 | 2 | 3202800 | 1170360 | 36.54 | 
| Swap DAI -> USDC | 2e-05 | 2.3620229e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.3608979200000003e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.3608979200000003e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00283072 | 0.0033399398909248 | 4 | 30 | 4241520 | 1415360 | 33.37 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.3597811800000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.3597811800000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.3597811800000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.53967177e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00290072 | 0.0034225322322248 | 3 | 31 | 3292800 | 1450360 | 44.05 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.3597811800000003e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0012152873077000003 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0006607387303999999 | 4 | 30 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.3597811800000003e-05 | 23 | 1 | 1937440 | 10000 | 0.52 |

**Pull request closed without merging**
