### PR TITLE
ci refactoring

### PR DESCRIPTION
**Pull request by kristinaNikolaevaa**

### CODE REVIEW

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0008404362079999999 | 10 | 1 | 1192320 | 1172320 | 98.32 | 
| Direct swap | 2e-05 | 7.169e-06 | 19 | 1 | 130000 | 10000 | 7.69 |

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getAccountInfo                    |   57953 |      0     |      0.157 |    0.00152158  |         0     |
| getSlot                           |   57933 |      0     |      0.117 |    0.000854832 |         0     |
| getBlocks                         |   23448 |      0     |      0.162 |    0.000625853 |         0     |
| getBlock                          |   15108 |      0     |      0.048 |    0.00137338  |         0.001 |
| getMultipleAccounts               |   13754 |      0     |      0.103 |    0.00191181  |         0.001 |
| getTransaction                    |    7917 |      0     |      0.157 |    0.0095425   |         0.003 |
| getBlockTime                      |    6216 |      0     |      0.066 |    0.000507561 |         0     |
| sendTransaction                   |    5146 |      0     |      0.156 |    0.00720735  |         0.003 |
| getLatestBlockhash                |    4938 |      0     |      0.109 |    0.00218104  |         0.001 |
| getBalance                        |    1816 |      0     |      0.154 |    0.00167456  |         0.001 |
| getSignatureStatuses              |    1094 |      0     |      0.073 |    0.00149543  |         0     |
| getVersion                        |     585 |      0     |      0.07  |    0.00185299  |         0     |
| isBlockhashValid                  |     529 |      0     |      0.041 |    0.000640832 |         0     |
| getSignaturesForAddress           |      60 |      0     |      0.004 |    0.00153333  |         0.002 |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000315789 |         0     |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.000875    |         0.001 |
| getTokenAccountBalance            |      10 |      0     |      0.021 |    0.0023      |         0     |
| getHealth                         |       3 |      0.001 |      0.001 |    0.001       |         0.001 |
| getFirstAvailableBlock            |       2 |      0     |      0     |    0           |         0     |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |         0.001 |
| getClusterNodes                   |       1 |      0     |      0     |    0           |         0     |

</details>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0008313624512 | 10 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0008313390048 | 10 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00797264 | 0.0028267792383999996 | 4 | 2 | 4156320 | 3986320 | 95.91 | 
| Borrow from lending pool | 0.00477928 | 0.0016945893096000002 | 5 | 10 | 2644640 | 2389640 | 90.36 | 
| Repay | 0.00013 | 4.6092799999999993e-05 | 5 | 10 | 290000 | 65000 | 22.41 | 
| Flashloan | 0.00473928 | 0.0016804539024000001 | 4 | 7 | 2634640 | 2369640 | 89.94 | 
| Withdraw | 7e-05 | 2.4819199999999998e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00247464 | 0.0008774578512 | 5 | 11 | 1752320 | 1237320 | 70.61 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0008313624512 | 10 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02747064 | 0.0097405395312 | 4 | 7 | 14000320 | 13735320 | 98.11 | 
| NonfungiblePositionManager - Increase liquidity  | 8e-05 | 2.83648e-05 | 23 | 6 | 230000 | 40000 | 17.39 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0004957172256 | 18 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 2e-05 | 7.0902e-06 | 21 | 1 | 80000 | 10000 | 12.5 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 7.0902e-06 | 16 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 7.089600000000001e-06 | 18 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.0001699379136 | 12 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0008311983263999999 | 13 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0008347434263999999 | 4 | 2 | 1432320 | 1177320 | 82.2 | 
| Swap DAI -> USDC | 2e-05 | 7.0902e-06 | 22 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 7.0902e-06 | 22 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 7.0902e-06 | 24 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00241464 | 0.0008560140264 | 4 | 7 | 1492320 | 1207320 | 80.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 7.089600000000001e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 7.089600000000001e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 7.089600000000001e-06 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 3e-05 | 1.0634400000000001e-05 | 4 | 2 | 180000 | 15000 | 8.33 | 
| Add liquidity in metapool | 0.00241464 | 0.0008559415872 | 4 | 7 | 1522320 | 1207320 | 79.31 | 
| Swap SUSD -> LP metapool | 2e-05 | 7.089600000000001e-06 | 23 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00015 | 5.3172e-05 | 5 | 11 | 560000 | 75000 | 13.39 | 
| Swap DAI -> USDT metapool | 0.00013 | 4.60824e-05 | 4 | 7 | 330000 | 65000 | 19.7 | 
| Remove liquidity in Metapool | 2e-05 | 7.089600000000001e-06 | 24 | 1 | 100000 | 10000 | 10.0 |

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getAccountInfo                    |   58224 |      0     |      0.082 |    0.00141507  |        0      |
| getSlot                           |   55986 |      0     |      0.114 |    0.000917926 |        0      |
| getBlocks                         |   22223 |      0     |      0.057 |    0.000660487 |        0.001  |
| getBlock                          |   14404 |      0     |      0.044 |    0.00148931  |        0.001  |
| getMultipleAccounts               |   13602 |      0     |      0.106 |    0.00203198  |        0.001  |
| getTransaction                    |    8062 |      0     |      0.215 |    0.00937038  |        0.004  |
| getBlockTime                      |    6247 |      0     |      0.084 |    0.000498159 |        0      |
| sendTransaction                   |    5201 |      0     |      0.12  |    0.00793828  |        0.003  |
| getLatestBlockhash                |    4991 |      0     |      0.089 |    0.00245742  |        0.001  |
| getBalance                        |    1824 |      0     |      0.036 |    0.00141721  |        0.001  |
| getSignatureStatuses              |    1111 |      0     |      0.028 |    0.0009973   |        0      |
| getVersion                        |     580 |      0     |      0.04  |    0.0010931   |        0      |
| isBlockhashValid                  |     537 |      0     |      0.027 |    0.000513966 |        0      |
| getSignaturesForAddress           |      59 |      0     |      0.004 |    0.00152542  |        0.001  |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000289474 |        0      |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.0005      |        0.0005 |
| getHealth                         |       3 |      0     |      0.001 |    0.000333333 |        0      |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000666667 |        0.001  |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |        0.001  |
| getClusterNodes                   |       1 |      0     |      0     |    0           |        0      |

</details>

**Review by IvanAdamovNeon — APPROVED** [review]

**Pull request merged**
