### PR TITLE
NDEV-2768 Replace SELFDESTRUCT opcode with SENDALL

### PR DESCRIPTION
**Pull request by s-medvedev**

### CODE REVIEW

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Review by anton-lisanin — APPROVED** [review]

**Pull request merged**
