### PR TITLE
NDEV-3101. Add execution map into EmulationRequest

### PR DESCRIPTION
**Pull request by ancientmage**

### CODE REVIEW

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

🔗[Cost report](https://github.com/neonlabsorg/neon-proxy.py/actions/runs/10940199633/artifacts/1952868200)

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   64794 |      0     |      0.194 |    0.00113524  |         0.001 |
| getAccountInfo                    |   59574 |      0     |      0.189 |    0.00217654  |         0.001 |
| getBlocks                         |   26785 |      0     |      0.1   |    0.000754863 |         0.001 |
| getBlock                          |   17262 |      0     |      0.044 |    0.00183994  |         0.002 |
| getMultipleAccounts               |   14926 |      0     |      0.189 |    0.00266609  |         0.001 |
| getLatestBlockhash                |   11890 |      0     |      0.132 |    0.00194836  |         0.001 |
| getTransaction                    |    8116 |      0     |      0.192 |    0.0125238   |         0.005 |
| getBlockTime                      |    6510 |      0     |      0.058 |    0.000730568 |         0     |
| sendTransaction                   |    5289 |      0     |      0.132 |    0.00922859  |         0.005 |
| getBalance                        |    1853 |      0     |      0.042 |    0.00228009  |         0.001 |
| getSignatureStatuses              |    1175 |      0     |      0.189 |    0.00205277  |         0.001 |
| getVersion                        |     624 |      0     |      0.062 |    0.00196314  |         0     |
| isBlockhashValid                  |     569 |      0     |      0.028 |    0.00086116  |         0     |
| getSignaturesForAddress           |      62 |      0     |      0.004 |    0.00162903  |         0.001 |
| simulateTransaction               |      56 |      0     |      0.001 |    0.000660714 |         0.001 |
| requestAirdrop                    |      32 |      0     |      0.002 |    0.0009375   |         0.001 |
| getTokenAccountBalance            |       9 |      0     |      0.053 |    0.00644444  |         0.001 |
| getHealth                         |       3 |      0     |      0     |    0           |         0     |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |         0     |
| getClusterNodes                   |       1 |      0     |      0     |    0           |         0     |

</details>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

🔗[Cost report](https://github.com/neonlabsorg/neon-proxy.py/actions/runs/11056797611/artifacts/1983686463)

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   59413 |      0     |      0.298 |    0.000832528 |        0      |
| getAccountInfo                    |   58453 |      0     |      0.123 |    0.00124238  |        0      |
| getBlocks                         |   23836 |      0     |      0.026 |    0.000561923 |        0      |
| getBlock                          |   15295 |      0     |      0.045 |    0.00128741  |        0.001  |
| getMultipleAccounts               |   14164 |      0     |      0.098 |    0.00185689  |        0.001  |
| getLatestBlockhash                |   11069 |      0     |      0.085 |    0.00164568  |        0      |
| getTransaction                    |    8165 |      0     |      0.124 |    0.0098692   |        0.004  |
| getBlockTime                      |    6381 |      0     |      0.03  |    0.00036499  |        0      |
| sendTransaction                   |    5266 |      0     |      0.298 |    0.00790695  |        0.003  |
| getBalance                        |    1839 |      0     |      0.064 |    0.00122675  |        0.001  |
| getSignatureStatuses              |    1144 |      0     |      0.048 |    0.000931818 |        0      |
| getVersion                        |     596 |      0     |      0.107 |    0.000989933 |        0      |
| isBlockhashValid                  |     554 |      0     |      0.022 |    0.000458484 |        0      |
| getSignaturesForAddress           |      62 |      0     |      0.006 |    0.00108065  |        0.001  |
| simulateTransaction               |      56 |      0     |      0.001 |    0.000375    |        0      |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.00065625  |        0.001  |
| getHealth                         |       3 |      0     |      0.001 |    0.000333333 |        0      |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000333333 |        0      |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |        0      |
| getClusterNodes                   |       1 |      0.004 |      0.004 |    0.004       |        0.004  |

</details>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

🔗[Cost report](https://github.com/neonlabsorg/neon-proxy.py/actions/runs/11073450156/artifacts/1988295080)

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   72146 |          0 |      0.41  |    0.000597303 |        0      |
| getAccountInfo                    |   58117 |          0 |      0.104 |    0.000981417 |        0      |
| getBlocks                         |   28431 |          0 |      0.035 |    0.000450529 |        0      |
| getBlock                          |   17107 |          0 |      0.132 |    0.00102023  |        0.001  |
| getMultipleAccounts               |   14265 |          0 |      0.186 |    0.00136719  |        0.001  |
| getLatestBlockhash                |   11847 |          0 |      0.126 |    0.00106964  |        0      |
| getTransaction                    |    8135 |          0 |      0.117 |    0.00797074  |        0.003  |
| getBlockTime                      |    6082 |          0 |      0.051 |    0.000283788 |        0      |
| sendTransaction                   |    5259 |          0 |      0.112 |    0.00677429  |        0.003  |
| getBalance                        |    1832 |          0 |      0.028 |    0.000865175 |        0      |
| getSignatureStatuses              |    1144 |          0 |      0.045 |    0.000756119 |        0      |
| getVersion                        |     600 |          0 |      0.036 |    0.00081     |        0      |
| isBlockhashValid                  |     554 |          0 |      0.011 |    0.000270758 |        0      |
| getSignaturesForAddress           |      63 |          0 |      0.002 |    0.00084127  |        0.001  |
| simulateTransaction               |      38 |          0 |      0.001 |    0.000210526 |        0      |
| requestAirdrop                    |      32 |          0 |      0.001 |    0.0005625   |        0.001  |
| getTokenAccountBalance            |       5 |          0 |      0.001 |    0.0002      |        0      |
| getHealth                         |       3 |          0 |      0.001 |    0.000333333 |        0      |
| getFirstAvailableBlock            |       2 |          0 |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |          0 |      0     |    0           |        0      |
| getClusterNodes                   |       1 |          0 |      0     |    0           |        0      |

</details>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

🔗[Cost report](https://github.com/neonlabsorg/neon-proxy.py/actions/runs/11176442222/artifacts/2014845735)

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   63289 |      0     |      0.191 |    0.000622652 |        0      |
| getAccountInfo                    |   58061 |      0     |      0.121 |    0.000940459 |        0      |
| getBlocks                         |   26460 |      0     |      0.069 |    0.000426644 |        0      |
| getBlock                          |   17238 |      0     |      0.026 |    0.000989616 |        0.001  |
| getMultipleAccounts               |   14607 |      0     |      0.145 |    0.00142062  |        0.001  |
| getLatestBlockhash                |   11779 |      0     |      0.118 |    0.00122854  |        0      |
| getTransaction                    |    8051 |      0     |      0.303 |    0.00861558  |        0.003  |
| getBlockTime                      |    6321 |      0     |      0.043 |    0.000288404 |        0      |
| sendTransaction                   |    5213 |      0     |      0.176 |    0.00631383  |        0.003  |
| getBalance                        |    1821 |      0     |      0.115 |    0.000998902 |        0      |
| getSignatureStatuses              |    1160 |      0     |      0.028 |    0.000749138 |        0      |
| getVersion                        |     608 |      0     |      0.089 |    0.000740132 |        0      |
| isBlockhashValid                  |     562 |      0     |      0.011 |    0.00025089  |        0      |
| getSignaturesForAddress           |      60 |      0     |      0.004 |    0.000933333 |        0.001  |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000289474 |        0      |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.0005      |        0.0005 |
| getTokenAccountBalance            |       5 |      0     |      0.002 |    0.0006      |        0      |
| getHealth                         |       3 |      0     |      0.025 |    0.00866667  |        0.001  |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |        0      |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |        0.001  |

</details>

**Review by s-medvedev — APPROVED** [review]

**Pull request merged**
