### PR TITLE
NDEV-2651 Remove syscall_stabs

### PR DESCRIPTION
**Pull request by s-medvedev**
1. Use AccountStorage to access Rent sysvar and return_data()
2. Implement `log_data()` and `log_msg()` to work with our implementation instead of syscall_stab in emulation context

### CODE REVIEW

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Compound-Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| borrow erc20 cToken | 0.00501728 | 0.0064327149455328005 | 16 | 1 | 4062432 | 2508640 | 61.75 | 
| borrow ether cToken | 0.00274832 | 0.0035236540793232 | 13 | 1 | 2539856 | 1374160 | 54.1 | 
| Repay borrow erc20 cToken | 2e-05 | 2.5642240200000003e-05 | 17 | 1 | 1362240 | 10000 | 0.73 | 
| Mint erc20 cToken | 2e-05 | 2.5642240200000003e-05 | 16 | 1 | 1087592 | 10000 | 0.92 | 
| Mint ether cToken | 2e-05 | 2.5642240200000003e-05 | 11 | 1 | 296648 | 10000 | 3.37 | 
| Transfer erc20 cToken | 0.0113648 | 0.014570946571248 | 21 | 1 | 6635288 | 5682400 | 85.64 | 
| Add reserves for ether cToken | 2e-05 | 2.5642240200000003e-05 | 9 | 1 | 27500 | 10000 | 36.36 | 
| Liquidate borrow | 2e-05 | 2.5642240200000003e-05 | 20 | 1 | 1680888 | 10000 | 0.59 | 
| Redeem erc20 cToken | 2e-05 | 2.5642240200000003e-05 | 16 | 1 | 823944 | 10000 | 1.21 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.0029347031064096 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.0029347031064096 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.009982011265056 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.006523283337919201 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0006282348849 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.0064335354972192005 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 8.974784069999999e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0043065629571096 | 4 | 57 | 4940000 | 1679480 | 34.0 | 

Cost report for "Curve-Factory" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Deploy factory | 0.26453552 | 0.3391641672635953 | 3 | 25 | 3709916 | 132267760 | 3565.25 | 
| Deploy 2 | 0.99434744 | 1.2748647949367544 | 3 | 70 | 15002666 | 497173720 | 3313.9 | 
| Deploy 3 | 1.02243016 | 1.3108699875222218 | 3 | 72 | 15483729 | 511215080 | 3301.63 | 
| Deploy 4 | 1.04590536 | 1.3409678233793736 | 3 | 74 | 15885269 | 522952680 | 3292.06 | 

Cost report for "Robonomics" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| PublicAmbix setSink | 0.00455792 | 0.0058437639726192005 | 10 | 1 | 199023640 | 2278960 | 1.15 | 
| PublicAmbix appendSource | 0.00909584 | 0.0116618857050384 | 12 | 1 | 199023640 | 4547920 | 2.29 | 
| XRT approve | 0.00228896 | 0.0029347031064096 | 9 | 1 | 199022872 | 1144480 | 0.58 | 
| PublicAmbix run | 2e-05 | 2.5642240200000003e-05 | 20 | 1 | 199021400 | 10000 | 0.01 | 
| KycAmbix setSink | 0.00455792 | 0.0058437639726192005 | 10 | 1 | 199023576 | 2278960 | 1.15 | 
| KycAmbix appendSource | 0.00909584 | 0.0116618857050384 | 12 | 1 | 199023576 | 4547920 | 2.29 | 
| KycAmbix run | 2e-05 | 2.5642240200000003e-05 | 19 | 1 | 199021400 | 10000 | 0.01 | 
| DutchAuction started | 2e-05 | 2.5642240200000003e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction bid | 0.00228896 | 0.0029347031064096 | 13 | 1 | 199026136 | 1144480 | 0.58 | 
| DutchAuction update stage | 2e-05 | 2.5642240200000003e-05 | 8 | 1 | 199021272 | 10000 | 0.01 | 
| DutchAuction claim tokens | 2e-05 | 2.5642240200000003e-05 | 12 | 1 | 199021272 | 10000 | 0.01 | 
| XRT transfer | 0.00228896 | 0.0029347031064096 | 10 | 1 | 199023192 | 1144480 | 0.58 | 
| Factory create lighthouse | 0.04148768 | 0.053191852795036805 | 18 | 1 | 199022488 | 20743840 | 10.42 | 
| XRT increase allowance | 0.00228896 | 0.0029347031064096 | 9 | 1 | 199022872 | 1144480 | 0.58 | 

Cost report for "Curve" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Metapool: add liquidity | 0.01636416 | 0.0209806860695616 | 22 | 229 | 12265088 | 8182080 | 66.71 | 
| Metapool: swap 1 | 0.00458 | 0.0058720730058000005 | 19 | 230 | 4803832 | 2290000 | 47.67 | 
| Metapool: swap 2 | 0.00464 | 0.0059489997264 | 19 | 233 | 4836832 | 2320000 | 47.97 | 
| Metapool: withdraw admin fees | 2e-05 | 2.5642240200000003e-05 | 15 | 1 | 549296 | 10000 | 1.82 | 
| Pool: add liquidity | 0.01378896 | 0.0176789912214096 | 26 | 577 | 11132000 | 6894480 | 61.93 | 
| Pool: swap 1 | 0.00542 | 0.006949047094200001 | 19 | 272 | 5265832 | 2710000 | 51.46 | 
| Pool: swap 2 | 0.00542 | 0.006949047094200001 | 19 | 272 | 5265832 | 2710000 | 51.46 | 
| Pool: swap 3 | 0.00542 | 0.006949047094200001 | 19 | 272 | 5265832 | 2710000 | 51.46 | 
| Pool: withdraw admin fees | 2e-05 | 2.5642240200000003e-05 | 16 | 1 | 55000 | 10000 | 18.18 | 
| Stablecoin: transfer | 2e-05 | 2.5642240200000003e-05 | 10 | 1 | 538296 | 10000 | 1.86 | 
| Tri pool: add liquidity | 0.01528248 | 0.0195938511505848 | 3 | 39 | 13165240 | 7641240 | 58.04 | 
| Tri pool: swap 1 | 0.00072 | 0.0009231206472000001 | 20 | 37 | 2680832 | 360000 | 13.43 | 
| Tri pool: swap 2 | 0.00072 | 0.0009231206472000001 | 20 | 37 | 2680832 | 360000 | 13.43 | 
| Tri pool: swap 3 | 0.0007 | 0.0008974784070000001 | 20 | 36 | 2669832 | 350000 | 13.11 | 
| Tri pool: apply new fee | 2e-05 | 2.5642240200000003e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Tri pool: withdraw admin fees | 2e-05 | 2.5642240200000003e-05 | 18 | 1 | 560296 | 10000 | 1.78 | 
| gauge v3: deposit | 0.01863104 | 0.023887080142790403 | 28 | 1 | 10840368 | 9315520 | 85.93 | 
| gauge controller: vote | 0.01774016 | 0.022744872195321602 | 26 | 1 | 14210856 | 8870080 | 62.42 | 
| gauge controller: vote | 0.01047392 | 0.0134287386237792 | 26 | 1 | 10229736 | 5236960 | 51.19 | 
| gauge controller: vote | 0.01047392 | 0.0134287386237792 | 26 | 1 | 10229736 | 5236960 | 51.19 | 
| gauge controller: vote | 0.0077456 | 0.009930726784656 | 26 | 1 | 8239176 | 3872800 | 47.0 | 
| gauge controller: vote | 0.00547664 | 0.0070216659184464 | 26 | 1 | 7243896 | 2738320 | 37.8 | 
| gauge controller: vote | 0.00547664 | 0.0070216659184464 | 26 | 1 | 7243896 | 2738320 | 37.8 | 
| gauge controller: vote | 0.0077456 | 0.009930726784656 | 26 | 1 | 8239176 | 3872800 | 47.0 | 
| gauge controller: vote | 0.00547664 | 0.0070216659184464 | 26 | 1 | 7243896 | 2738320 | 37.8 | 
| gauge controller: vote | 0.00547664 | 0.0070216659184464 | 26 | 1 | 7243896 | 2738320 | 37.8 | 

Cost report for "Uniswap V2" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0029347031064096 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Direct swap | 2e-05 | 2.5642240200000003e-05 | 18 | 1 | 1048720 | 10000 | 0.95 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0029347031064096 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.035006581183118404 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0005641292844000001 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0017924951589408 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.0058437639726192005 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.5642240200000003e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.5642240200000003e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0006145932131136001 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.0029347031064096 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Yearn" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Create new release | 0.00228896 | 0.0029347031064096 | 13 | 1 | 1291928 | 1144480 | 88.59 | 
| Clone strategy | 0.03870368 | 0.0496224529591968 | 15 | 1 | 21364024 | 19351840 | 90.58 | 
| Set strategist authority | 2e-05 | 2.5642240200000003e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Set emergency shutdown | 2e-05 | 2.5642240200000003e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Emergency shutdown | 2e-05 | 2.5642240200000003e-05 | 8 | 1 | 27500 | 10000 | 36.36 | 
| Call strategy harvest | 0.00682688 | 0.0087528248388288 | 22 | 1 | 7700880 | 3413440 | 44.33 | 
| Withdraw from vault | 2e-05 | 2.5642240200000003e-05 | 14 | 1 | 823944 | 10000 | 1.21 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.0029475242265096 | 3 | 2 | 3181920 | 1149480 | 36.13 | 
| Swap DAI -> USDC | 2e-05 | 2.5642240200000003e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.5642240200000003e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.5642240200000003e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.0035757591114096003 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.5642240200000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.5642240200000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.5642240200000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.84633603e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.0036655069521096 | 3 | 31 | 3271920 | 1429480 | 43.69 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.5642240200000003e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0013205753703000001 | 4 | 54 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0007179827255999999 | 4 | 31 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.5642240200000003e-05 | 23 | 1 | 1937440 | 10000 | 0.52 |

**Review by anton-lisanin — APPROVED** [review]

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.0029987737748928002 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.0029987737748928002 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.010199939318208 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.0066657001715856 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0006419505582 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.006573992948985601 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 9.170722259999999e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0044005841774928 | 4 | 57 | 4710320 | 1679480 | 35.66 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0029987737748928002 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.0357708476102112 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0005764453992000001 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0018316290538944 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.0059713454861856 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.6202063600000003e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.6202063600000003e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0006280110603648 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.0029987737748928002 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.0030118748066928 | 3 | 2 | 3181920 | 1149480 | 36.13 | 
| Swap DAI -> USDC | 2e-05 | 2.6202063600000003e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.6202063600000003e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.6202063600000003e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.0036538253648928003 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.6202063600000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.6202063600000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.6202063600000003e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.93030954e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.0037455325874928 | 3 | 31 | 3271920 | 1429480 | 43.69 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.6202063600000003e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0013494062754000002 | 4 | 52 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0007336577807999999 | 4 | 29 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.6202063600000003e-05 | 23 | 1 | 1937440 | 10000 | 0.52 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00228896 | 0.0029738544396128 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Token approve | 0.00228896 | 0.0029738544396128 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| Deposit to lending pool | 0.0077856 | 0.010115179437408 | 4 | 5 | 4761840 | 3892800 | 81.75 | 
| Borrow from lending pool | 0.00508792 | 0.0066103092585256 | 4 | 30 | 3737360 | 2543960 | 68.07 | 
| Repay | 0.00049 | 0.0006366160507 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00501792 | 0.006519364108425601 | 4 | 28 | 7360480 | 2508960 | 34.09 | 
| Withdraw | 7e-05 | 9.094515009999999e-05 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00335896 | 0.0043640160197128 | 4 | 57 | 4940000 | 1679480 | 34.0 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00228896 | 0.0029738544396128 | 9 | 1 | 1164480 | 1144480 | 98.28 | 
| NonfungiblePositionManager - Mint position | 0.02730384 | 0.035473597530091196 | 4 | 28 | 30739120 | 13651920 | 44.41 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0005716552292 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0018164085064543997 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00455792 | 0.0059217245506255995 | 20 | 1 | 3497360 | 2278960 | 65.16 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 2.59843286e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 2.59843286e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0006227923878848 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00228896 | 0.0029738544396128 | 12 | 1 | 1633840 | 1144480 | 70.05 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00229896 | 0.0029868466039128 | 3 | 2 | 3181920 | 1149480 | 36.13 | 
| Swap DAI -> USDC | 2e-05 | 2.59843286e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 2.59843286e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 2.59843286e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00278896 | 0.0036234626546128 | 4 | 30 | 4220640 | 1394480 | 33.04 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 2.59843286e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 2.59843286e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 2.59843286e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 3.89764929e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00285896 | 0.0037144078047127997 | 3 | 31 | 3271920 | 1429480 | 43.69 | 
| Swap SUSD -> LP metapool | 2e-05 | 2.59843286e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0013381929229000001 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0007275612007999999 | 4 | 30 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 2.59843286e-05 | 23 | 1 | 1937440 | 10000 | 0.52 |

**Pull request merged**
