### PR TITLE
Update Buffer ser/de variant indices

### PR DESCRIPTION
**Pull request by mickvangelderen**

### CODE REVIEW

**Review by andreisilviudragnea — COMMENTED** [review]
There needs to be a unit test which verifies if the serde serialization code before and after #259 depends on the values of these numbers or not.

**Comment by mickvangelderen** [comment]
> There needs to be a unit test which verifies if the serde serialization code before and after #259 depends on the values of these numbers or not.

@andreisilviudragnea Do you mean if the serialized value depends on the variant indices? It probably does, given that you need to supply them as well in the deserialization implementation.

@anton-lisanin mentioned that we are free to change the serialized format. It does not need to be backwards compatible.

I do think it would be a good idea to assert that serializing and deserializing gives back something equivalent to the original, if we don't already have those tests.

**Comment by andreisilviudragnea** [comment]
I know from previous experience that changing serialization code without unit tests is dangerous.

The concrete serialization framework which should be tested here is `bincode`.

**Comment by mickvangelderen** [comment]
> I know from previous experience that changing serialization code without unit tests is dangerous.

That goes for pretty much any code :clown_face: . 

So to your knowledge there are no unit tests for this. I suppose our integration tests should catch problems with the serialization but having it unit tested would give a better guarantee and earlier feedback.

**Comment by mickvangelderen** [comment]
@andreisilviudragnea FYI added tests.

**Comment by anton-lisanin** [comment]
> @anton-lisanin mentioned that we are free to change the serialized format. It does not need to be backwards compatible.

We need to keep backward compatibility for deserialization. 
It's ok to change serialization format, but deserialization function should handle both old and new formats.

**Review by anton-lisanin — CHANGES_REQUESTED** [review]
Rejected.
With this code, it is not possible to deserialize from the buffer that was serialized in the previous version.

**Comment by mickvangelderen** [comment]
> We need to keep backward compatibility for deserialization. It's ok to change serialization format, but deserialization function should handle both old and new formats.

Ah I misunderstood you then. We should have tests to assert we can deserialize the old format in that case. This also means that `develop` is currently broken since we [error on unknown variants](https://github.com/neonlabsorg/neon-evm/blob/b4afacd808031ee0dc4c3e9d8d489803a201770c/evm_loader/program/src/evm/buffer.rs#L204-L220) including the previously valid `0` variant (`buffer::Inner::Empty`).

**Comment by mickvangelderen** [comment]
This PR was made based on the assumption that we can make backwards incompatible changes to the serialized format which is not the case. I've opened https://github.com/neonlabsorg/neon-evm/pull/263 to implement unit tests which guarantee that the serialized data looks a certain way, and that serialized data from previous and the current version can be successfully deserialized.

**Pull request closed without merging**
