### PR TITLE
NDEV-3034: Remove unused solana_emulator module

### PR DESCRIPTION
**Pull request by andreisilviudragnea**

### CODE REVIEW

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0022652508178496 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.0265091164356096 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 5.79631884e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0013506195739712 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.004510772605539199 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.9323015000000002e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.9322763000000003e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.000463127983584 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0022653263152576 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0022653263152576 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0022653263152576 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.007683840768000001 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00475928 | 0.0045984163360000005 | 5 | 9 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 0.000106282088 | 5 | 9 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00470928 | 0.004550526309590399 | 5 | 8 | 2634640 | 2354640 | 89.37 | 
| Withdraw | 7e-05 | 6.76347385e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00247464 | 0.0023909574747744003 | 5 | 11 | 1752320 | 1237320 | 70.61 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0022653535599744 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.9323500000000002e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.9323500000000002e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.9325000000000002e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.0023041584 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.9325000000000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.9325000000000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.9325000000000002e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.9325000000000002e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.0023041584 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.9325000000000002e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00013 | 0.0001256125 | 5 | 9 | 560000 | 65000 | 11.61 | 
| Swap DAI -> USDT metapool | 0.0001 | 9.6625e-05 | 5 | 8 | 330000 | 50000 | 15.15 | 
| Remove liquidity in Metapool | 2e-05 | 1.9325000000000002e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0020958764626752002 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.0245292204759552 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 5.3634070800000006e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0012500815999744 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0041738749017504 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.7878023600000003e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.7878023600000003e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00042850046964480005 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0020958764626752002 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0020958764626752002 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0020954945442656 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.007108874280115201 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00475928 | 0.004254326007950401 | 5 | 9 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 9.832912980000001e-05 | 5 | 9 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00470928 | 0.0042096309489504 | 5 | 8 | 2634640 | 2354640 | 89.37 | 
| Withdraw | 7e-05 | 6.25730826e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00247464 | 0.0022120836160752005 | 5 | 11 | 1752320 | 1237320 | 70.61 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0020958764626752002 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.7878023600000003e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.78782004e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.78782004e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.0021316325098752003 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.7878023600000003e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.7878023600000003e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.78726534e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.78726534e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.0021309922101888 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.78726534e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00013 | 0.0001162071534 | 5 | 10 | 560000 | 65000 | 11.61 | 
| Swap DAI -> USDT metapool | 0.0001 | 8.939011800000001e-05 | 5 | 8 | 330000 | 50000 | 15.15 | 
| Remove liquidity in Metapool | 2e-05 | 1.7878023600000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0022458918991008 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.026284770269568 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 5.7472647000000005e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0013388280973472 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0044713916645552 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.91535906e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.91535176e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.0004590715098368 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.002245325387184 | 12 | 1 | 1202320 | 1172320 | 97.5 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0021241943212032 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02744064 | 0.0248606402936832 | 5 | 8 | 14000320 | 13720320 | 98.0 | 
| NonfungiblePositionManager - Increase liquidity  | 6e-05 | 5.43622278e-05 | 4 | 5 | 230000 | 30000 | 13.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0012667123907104 | 17 | 1 | 829040 | 699040 | 84.32 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.004230541050366399 | 20 | 1 | 2404640 | 2334640 | 97.09 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 1.8120742600000002e-05 | 15 | 1 | 50000 | 10000 | 20.0 | 
| Direct swap | 2e-05 | 1.8120561e-05 | 17 | 1 | 180000 | 10000 | 5.56 | 
| Burn transaction | 0.00047936 | 0.00043430806464640005 | 11 | 1 | 279680 | 239680 | 85.7 | 
| Collect transaction | 0.00234464 | 0.0021242825031136 | 12 | 1 | 1202320 | 1172320 | 97.5 | 

Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0021243096071519997 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0021243308964832 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.0072054591724416 | 5 | 5 | 4156320 | 3976320 | 95.67 | 
| Borrow from lending pool | 0.00475928 | 0.0043121275111432005 | 5 | 9 | 2644640 | 2379640 | 89.98 | 
| Repay | 0.00011 | 9.96650809e-05 | 5 | 9 | 290000 | 55000 | 18.97 | 
| Flashloan | 0.00470928 | 0.0042668252016432 | 5 | 8 | 2634640 | 2354640 | 89.37 | 
| Withdraw | 7e-05 | 6.34219649e-05 | 5 | 5 | 250000 | 35000 | 14.0 | 
| Liquidation | 0.00247464 | 0.0022420933031448 | 5 | 11 | 1752320 | 1237320 | 70.61 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00234464 | 0.0021243096540448 | 5 | 4 | 1432320 | 1172320 | 81.85 | 
| Swap DAI -> USDC | 2e-05 | 1.81205608e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Swap USDC -> DAI | 2e-05 | 1.8120797600000003e-05 | 21 | 1 | 190000 | 10000 | 5.26 | 
| Remove liquidity | 2e-05 | 1.8120797600000003e-05 | 23 | 1 | 100000 | 10000 | 10.0 | 
| Add liquidity in 3 Tokens | 0.00238464 | 0.002160580060224 | 5 | 8 | 1492320 | 1192320 | 79.9 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 1.8120561400000004e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 1.8120561400000004e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 1.8120561400000004e-05 | 21 | 1 | 200000 | 10000 | 5.0 | 
| Remove liquidity 3 pool | 2e-05 | 1.81209e-05 | 5 | 4 | 180000 | 10000 | 5.56 | 
| Add liquidity in metapool | 0.00238464 | 0.0021605911488 | 5 | 8 | 1522320 | 1192320 | 78.32 | 
| Swap SUSD -> LP metapool | 2e-05 | 1.8121215200000003e-05 | 22 | 1 | 200000 | 10000 | 5.0 | 
| Swap USDC -> SUSD metapool | 0.00013 | 0.00011778366469999999 | 5 | 9 | 560000 | 65000 | 11.61 | 
| Swap DAI -> USDT metapool | 0.0001 | 9.0602819e-05 | 5 | 8 | 330000 | 50000 | 15.15 | 
| Remove liquidity in Metapool | 2e-05 | 1.8120563800000002e-05 | 23 | 1 | 100000 | 10000 | 10.0 |

**Review by s-medvedev — APPROVED** [review]

**Pull request merged**
