### PR TITLE
NDEV-2301 & NDEV-2328 & NDEV-2299: Implement debug_traceTransaction prestateTracer, callTracer & trace_replayTransaction stateDiff tracer 

### PR DESCRIPTION
**Pull request by andreisilviudragnea**
This PR fixes bugs related to the existing `struct_logger` tracer and implements 3 new tracers:
- [`debug_traceTransaction`](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugtracetransaction)([`prestateTracer`](https://geth.ethereum.org/docs/developers/evm-tracing/built-in-tracers#prestate-tracer) with both `pre` and `diffMode` modes and [`call_tracer`](https://geth.ethereum.org/docs/developers/evm-tracing/built-in-tracers#call-tracer) with `withLog` and `onlyTopCall` options)
- [`trace_replayTransaction`](https://openethereum.github.io/JSONRPC-trace-module#trace_replaytransaction)(`stateDiff` tracer)

### CODE REVIEW

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.004889043328 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.00488971917048 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.016585137276480002 | 4 | 5 | 4845360 | 3976320 | 82.06 | 
| Borrow from lending pool | 0.00519928 | 0.01084303734846 | 4 | 30 | 3793040 | 2599640 | 68.54 | 
| Repay | 0.00049 | 0.0010218892425 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00512928 | 0.01069705317096 | 4 | 28 | 7499680 | 2564640 | 34.2 | 
| Withdraw | 7e-05 | 0.00014596399999999997 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00341464 | 0.0071202073279999995 | 4 | 57 | 4967840 | 1707320 | 34.37 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0049092861590856 | 3 | 2 | 3209760 | 1177320 | 36.68 | 
| Swap DAI -> USDC | 2e-05 | 4.169882580000001e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 4.169882580000001e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 4.1702664400000004e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.0059314533629407995 | 4 | 30 | 4248480 | 1422320 | 33.48 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 4.1702664400000004e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 4.173367080000001e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 4.174056740000001e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 6.26280222e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00291464 | 0.0060871669682968 | 3 | 31 | 3299760 | 1457320 | 44.16 | 
| Swap SUSD -> LP metapool | 2e-05 | 4.1782609800000006e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0021531741605 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0011709065424 | 4 | 30 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 4.1818090800000004e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.004902418420665599 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.058253938663305596 | 4 | 28 | 31435120 | 13930320 | 44.31 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0009200460764000001 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0029235188385823997 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0097641181792 | 20 | 1 | 3553040 | 2334640 | 65.71 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 4.18411172e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 4.1850127600000005e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.001002912030624 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00234464 | 0.0049055999564672 | 12 | 1 | 1661680 | 1172320 | 70.55 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.004909899252496 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.004909899252496 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00796264 | 0.016674525805196003 | 4 | 5 | 4156320 | 3981320 | 95.79 | 
| Borrow from lending pool | 0.00519928 | 0.010884529474600798 | 4 | 30 | 3104000 | 2599640 | 83.75 | 
| Repay | 0.00049 | 0.0010257611293999999 | 4 | 27 | 1438400 | 245000 | 17.03 | 
| Flashloan | 0.00516928 | 0.0108213193693568 | 4 | 29 | 6580960 | 2584640 | 39.27 | 
| Withdraw | 7e-05 | 0.00014653730419999998 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00341464 | 0.007147182984000001 | 4 | 57 | 4967840 | 1707320 | 34.37 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0049284969840000005 | 3 | 2 | 3209760 | 1177320 | 36.68 | 
| Swap DAI -> USDC | 2e-05 | 4.186200000000001e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 4.186200000000001e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 4.186200000000001e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.0059495645599999996 | 4 | 30 | 4248480 | 1422320 | 33.48 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 4.1823839800000004e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 4.1823839800000004e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 4.18314242e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 6.276002580000001e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00291464 | 0.0060977183148536 | 3 | 31 | 3299760 | 1457320 | 44.16 | 
| Swap SUSD -> LP metapool | 2e-05 | 4.18514182e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0021548629897 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0011715759943999998 | 4 | 29 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 4.1847753600000004e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0049059247359999995 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.058295603136 | 4 | 28 | 31435120 | 13930320 | 44.31 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0009206505792 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0029252027700191995 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.009769534497307199 | 20 | 1 | 3553040 | 2334640 | 65.71 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 4.18459998e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 4.1849748800000004e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0010030547792384001 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00234464 | 0.0049061297513216 | 12 | 1 | 1661680 | 1172320 | 70.55 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.0043699741230656 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.0043665949106656 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.014802361998067202 | 4 | 5 | 4845360 | 3976320 | 82.06 | 
| Borrow from lending pool | 0.00519928 | 0.0096774938497544 | 4 | 30 | 3793040 | 2599640 | 68.54 | 
| Repay | 0.00049 | 0.0009120439727 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00512928 | 0.0095493843622944 | 4 | 28 | 7499680 | 2564640 | 34.2 | 
| Withdraw | 7e-05 | 0.0001303295 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00341464 | 0.0063574528301792 | 4 | 57 | 4967840 | 1707320 | 34.37 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.004381778067144 | 3 | 2 | 3209760 | 1177320 | 36.68 | 
| Swap DAI -> USDC | 2e-05 | 3.722585e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 3.7226152200000005e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 3.722585e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.0052947070972 | 4 | 30 | 4248480 | 1422320 | 33.48 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 3.72192422e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 3.7225483400000005e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 3.722284280000001e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 5.5822862100000005e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00291464 | 0.0054234379774824 | 3 | 31 | 3299760 | 1457320 | 44.16 | 
| Swap SUSD -> LP metapool | 2e-05 | 3.7215148200000003e-05 | 22 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0019161831497000001 | 4 | 53 | 3775520 | 515000 | 13.64 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.0010420547648 | 4 | 29 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 3.7216241600000006e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.0043628640960512 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.0518428582557312 | 4 | 28 | 30975760 | 13930320 | 44.97 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0008187485152 | 23 | 23 | 3904880 | 220000 | 5.63 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0026015361912064 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.0086885592433024 | 20 | 1 | 3553040 | 2334640 | 65.71 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 3.7216241600000006e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 3.7249916600000004e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0008931014210496001 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00234464 | 0.004369447704492799 | 12 | 1 | 1661680 | 1172320 | 70.55 |

**Comment by neonlabstech** [comment]
<details><summary>Dapps report</summary>


Cost report for "Aave" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token mint | 0.00234464 | 0.004324494812736 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Token approve | 0.00234464 | 0.004324494812736 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| Deposit to lending pool | 0.00795264 | 0.014667574531814402 | 4 | 5 | 4845360 | 3976320 | 82.06 | 
| Borrow from lending pool | 0.00519928 | 0.0095891208557096 | 4 | 30 | 3793040 | 2599640 | 68.54 | 
| Repay | 0.00049 | 0.00090373885 | 4 | 27 | 2586800 | 245000 | 9.47 | 
| Flashloan | 0.00512928 | 0.0094602645072 | 4 | 28 | 7499680 | 2564640 | 34.2 | 
| Withdraw | 7e-05 | 0.00012910555 | 4 | 5 | 1857760 | 35000 | 1.88 | 
| Liquidation | 0.00341464 | 0.0062978425036 | 4 | 57 | 4967840 | 1707320 | 34.37 | 

Cost report for "Saddle Finance" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Add liquidity | 0.00235464 | 0.0043427061834792 | 3 | 2 | 3209760 | 1177320 | 36.68 | 
| Swap DAI -> USDC | 2e-05 | 3.6880322e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Swap USDC -> DAI | 2e-05 | 3.6880322e-05 | 21 | 1 | 1797760 | 10000 | 0.56 | 
| Remove liquidity | 2e-05 | 3.68783154e-05 | 23 | 1 | 1937440 | 10000 | 0.52 | 
| Add liquidity in 3 Tokens | 0.00284464 | 0.0052465544536 | 4 | 30 | 4248480 | 1422320 | 33.48 | 
| Swap DAI -> USDC 3 pool | 2e-05 | 3.68873092e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> USDT 3 pool | 2e-05 | 3.68873e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Swap USDC -> DAI 3 pool | 2e-05 | 3.68873e-05 | 21 | 1 | 1807760 | 10000 | 0.55 | 
| Remove liquidity 3 pool | 3e-05 | 5.533096380000001e-05 | 3 | 2 | 2646480 | 15000 | 0.57 | 
| Add liquidity in metapool | 0.00291464 | 0.00536730956 | 3 | 31 | 3070080 | 1457320 | 47.47 | 
| Swap SUSD -> LP metapool | 2e-05 | 3.68109854e-05 | 22 | 1 | 1578080 | 10000 | 0.63 | 
| Swap USDC -> SUSD metapool | 0.00103 | 0.0018959190018000003 | 4 | 53 | 3545840 | 515000 | 14.52 | 
| Swap DAI -> USDT metapool | 0.00056 | 0.001030990996 | 4 | 30 | 3086160 | 280000 | 9.07 | 
| Remove liquidity in Metapool | 2e-05 | 3.6821107000000005e-05 | 23 | 1 | 1707760 | 10000 | 0.59 | 

Cost report for "Uniswap V3" dApp

| Action | Fee | Cost in $ | Accounts | TRx | Estimated Gas | Used Gas | Used % of EG |
| --- | --- | --- | --- | --- | --- | --- |--- |
| Token approve | 0.00234464 | 0.004316612015823999 | 9 | 1 | 1192320 | 1172320 | 98.32 | 
| NonfungiblePositionManager - Mint position | 0.02786064 | 0.051292980326424 | 4 | 28 | 31435120 | 13930320 | 44.31 | 
| NonfungiblePositionManager - Increase liquidity  | 0.00044 | 0.0008098635688 | 23 | 23 | 4364240 | 220000 | 5.04 | 
| NonfungiblePositionManager - Decrease Liquidity | 0.00139808 | 0.0025733046778815996 | 17 | 1 | 4274240 | 699040 | 16.35 | 
| NonfungiblePositionManager - Collect Fees | 0.00466928 | 0.008594272192105599 | 20 | 1 | 3553040 | 2334640 | 65.71 | 
| NonfungiblePositionManager - Burn Liquidity Position | 2e-05 | 3.6795101400000005e-05 | 15 | 1 | 3954560 | 10000 | 0.25 | 
| Direct swap | 2e-05 | 3.678807600000001e-05 | 17 | 1 | 1328400 | 10000 | 0.75 | 
| Burn transaction | 0.00047936 | 0.0008817366055680001 | 11 | 1 | 739040 | 239680 | 32.43 | 
| Collect transaction | 0.00234464 | 0.0043133625089088 | 12 | 1 | 1661680 | 1172320 | 70.55 |

**Review by anton-lisanin — APPROVED** [review]

**Pull request merged**
